name: Chip-8 Emulator CI

on:
  push:
    branches:
      - dev
      - staging
      - main
      
  pull_request:
    branches:
      - dev
      - staging
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Build
      run: cargo build --verbose
      
    - name: Run tests
      run: cargo test --verbose
